export enum Permission {
  USER_READ = 'user:read',
  USER_CREATE = 'user:create',
  USER_UPDATE = 'user:update',
  USER_DELETE = 'user:delete',
  CITIZEN_READ = 'citizen:read',
  CITIZEN_CREATE = 'citizen:create',
  CITIZEN_UPDATE = 'citizen:update',
  CITIZEN_DELETE = 'citizen:delete',
  LETTER_READ = 'letter:read',
  LETTER_CREATE = 'letter:create',
  LETTER_UPDATE = 'letter:update',
  LETTER_DELETE = 'letter:delete',
  LETTER_APPROVE = 'letter:approve',
  LETTER_SIGN = 'letter:sign',
  COMPLAINT_READ = 'complaint:read',
  COMPLAINT_CREATE = 'complaint:create',
  COMPLAINT_UPDATE = 'complaint:update',
  COMPLAINT_DELETE = 'complaint:delete',
  COMPLAINT_ASSIGN = 'complaint:assign',
  DASHBOARD_READ = 'dashboard:read',
  DASHBOARD_STATS = 'dashboard:stats',
  REPORT_READ = 'report:read',
  REPORT_EXPORT = 'report:export',
  SETTING_READ = 'setting:read',
  SETTING_UPDATE = 'setting:update',
  AUDIT_READ = 'audit:read',
}
