export enum ComplaintStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}

export enum ComplaintCategory {
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  SECURITY = 'SECURITY',
  SANITATION = 'SANITATION',
  WATER = 'WATER',
  ELECTRICITY = 'ELECTRICITY',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  SOCIAL = 'SOCIAL',
  ENVIRONMENT = 'ENVIRONMENT',
  OTHER = 'OTHER',
}
