export enum LetterStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SIGNED = 'SIGNED',
  PRINTED = 'PRINTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}
